pdf_dir: /data2/littraceqa/pdfs
docint_chunks: /data2/littraceqa/docint_chunks
chunks_dir: /data2/littraceqa/chunks
index_dir: /data2/littraceqa/index
backup_dir: /data2/littraceqa/backup
paper_metadata: data/paper_metadata.jsonl
